#!/bin/sh -x

python start.py -f 30 -d cpu_metrics &
python start.py -f 30 -d topn_cpu &
python start.py -f 30 -d topn_memory &
python start.py -f 30 -d topn_runtime &
python start.py -f 30 -d topn_swap &
#python start.py -f 30 -d cpu_metrics
